apiVersion: v1
kind: Secret
metadata:
  name: edu-db
  namespace: edu-platform
type: Opaque
stringData:
  POSTGRES_DB: edumsa
  POSTGRES_USER: edumsa
  POSTGRES_PASSWORD: change-me-in-real-env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edu-pgdata
  namespace: edu-platform
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: edu-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: edu-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "edumsa", "-d", "edumsa"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: edu-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: edu-platform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
